"""initial schema

Revision ID: e0a0cdd82362
Revises: 
Create Date: 2026-09-08 13:58:25.029896+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a0cdd82362'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_ref', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('asset_type', sa.Enum('Application', 'Database', 'Cloud Environment', 'Network', 'Endpoint', 'Third-Party Service', name='asset_type', native_enum=False, length=64), nullable=False),
    sa.Column('business_owner', sa.String(length=120), nullable=False),
    sa.Column('environment', sa.Enum('Production', 'Staging', 'Development', name='environment', native_enum=False, length=64), nullable=False),
    sa.Column('data_classification', sa.Enum('Public', 'Internal', 'Confidential', 'Restricted', name='data_classification', native_enum=False, length=64), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('criticality BETWEEN 1 AND 5', name='ck_assets_criticality'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_ref'), 'assets', ['asset_ref'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGIN_FAILED', 'EXPORT', name='audit_action', native_enum=False, length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_ref', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('control_type', sa.Enum('Preventive', 'Detective', 'Corrective', name='control_type', native_enum=False, length=64), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('testing_frequency', sa.Enum('Continuous', 'Monthly', 'Quarterly', 'Semi-Annual', 'Annual', name='testing_frequency', native_enum=False, length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_control_ref'), 'controls', ['control_ref'], unique=True)
    op.create_table('frameworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='user_role', native_enum=False, length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('control_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_ref', sa.String(length=20), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('assessor_id', sa.Integer(), nullable=True),
    sa.Column('implementation_status', sa.Enum('Implemented', 'Partially Implemented', 'Not Implemented', 'Not Applicable', name='implementation_status', native_enum=False, length=64), nullable=False),
    sa.Column('effectiveness', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('tester_comments', sa.Text(), nullable=True),
    sa.Column('remediation_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effectiveness >= 0 AND effectiveness <= 1', name='ck_assessments_effectiveness'),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessments_control_date', 'control_assessments', ['control_id', 'assessment_date'], unique=False)
    op.create_index(op.f('ix_control_assessments_assessment_ref'), 'control_assessments', ['assessment_ref'], unique=True)
    op.create_index(op.f('ix_control_assessments_control_id'), 'control_assessments', ['control_id'], unique=False)
    op.create_table('framework_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_framework_functions_framework_id'), 'framework_functions', ['framework_id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_ref', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('Identity & Access Management', 'Data Protection', 'Cloud Security', 'Application Security', 'Vulnerability Management', 'Incident Response', 'Business Continuity', 'Third-Party Risk', 'Security Awareness', name='risk_category', native_enum=False, length=64), nullable=False),
    sa.Column('threat', sa.Text(), nullable=False),
    sa.Column('vulnerability', sa.Text(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('inherent_score', sa.Integer(), nullable=False),
    sa.Column('residual_score', sa.Integer(), nullable=False),
    sa.Column('residual_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_owner', sa.String(length=120), nullable=False),
    sa.Column('treatment', sa.Enum('Mitigate', 'Accept', 'Transfer', 'Avoid', name='risk_treatment', native_enum=False, length=64), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Open', 'In Treatment', 'Monitoring', 'Closed', name='risk_status', native_enum=False, length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('impact BETWEEN 1 AND 5', name='ck_risks_impact'),
    sa.CheckConstraint('likelihood BETWEEN 1 AND 5', name='ck_risks_likelihood'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_asset_id'), 'risks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_risks_category'), 'risks', ['category'], unique=False)
    op.create_index('ix_risks_residual_score', 'risks', ['residual_score'], unique=False)
    op.create_index(op.f('ix_risks_risk_ref'), 'risks', ['risk_ref'], unique=True)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=20), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.Enum('Configuration Export', 'Scan Report', 'Policy Document', 'Plan Document', 'Test Result', 'Access Review', 'Screenshot', 'Log Extract', name='evidence_type', native_enum=False, length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Valid', 'Expiring', 'Expired', name='evidence_status', native_enum=False, length=64), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['control_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_assessment_id'), 'evidence', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_ref'), 'evidence', ['evidence_ref'], unique=True)
    op.create_table('framework_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['framework_functions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_framework_categories_function_id'), 'framework_categories', ['function_id'], unique=False)
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remediation_ref', sa.String(length=20), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=True),
    sa.Column('risk_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('Critical', 'High', 'Medium', 'Low', name='remediation_priority', native_enum=False, length=64), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Open', 'In Progress', 'Completed', 'Accepted Risk', name='remediation_status', native_enum=False, length=64), nullable=False),
    sa.Column('estimated_effort_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediations_control_id'), 'remediations', ['control_id'], unique=False)
    op.create_index(op.f('ix_remediations_priority'), 'remediations', ['priority'], unique=False)
    op.create_index(op.f('ix_remediations_remediation_ref'), 'remediations', ['remediation_ref'], unique=True)
    op.create_index(op.f('ix_remediations_risk_id'), 'remediations', ['risk_id'], unique=False)
    op.create_table('risk_controls',
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name='ck_risk_controls_weight'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('risk_id', 'control_id')
    )
    op.create_table('framework_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['framework_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_framework_subcategories_category_id'), 'framework_subcategories', ['category_id'], unique=False)
    op.create_index(op.f('ix_framework_subcategories_code'), 'framework_subcategories', ['code'], unique=True)
    op.create_table('framework_mappings',
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['framework_subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('control_id', 'subcategory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('framework_mappings')
    op.drop_index(op.f('ix_framework_subcategories_code'), table_name='framework_subcategories')
    op.drop_index(op.f('ix_framework_subcategories_category_id'), table_name='framework_subcategories')
    op.drop_table('framework_subcategories')
    op.drop_table('risk_controls')
    op.drop_index(op.f('ix_remediations_risk_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_remediation_ref'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_priority'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_control_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_framework_categories_function_id'), table_name='framework_categories')
    op.drop_table('framework_categories')
    op.drop_index(op.f('ix_evidence_evidence_ref'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_assessment_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_risks_risk_ref'), table_name='risks')
    op.drop_index('ix_risks_residual_score', table_name='risks')
    op.drop_index(op.f('ix_risks_category'), table_name='risks')
    op.drop_index(op.f('ix_risks_asset_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_framework_functions_framework_id'), table_name='framework_functions')
    op.drop_table('framework_functions')
    op.drop_index(op.f('ix_control_assessments_control_id'), table_name='control_assessments')
    op.drop_index(op.f('ix_control_assessments_assessment_ref'), table_name='control_assessments')
    op.drop_index('ix_assessments_control_date', table_name='control_assessments')
    op.drop_table('control_assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('frameworks')
    op.drop_index(op.f('ix_controls_control_ref'), table_name='controls')
    op.drop_table('controls')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_asset_ref'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
